name: Node.js CI
on: [push]
jobs:
  build:
    name: Node.js ${{ matrix.node-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Validate
      run: |
        npm install -g npm
        npm --version
        npm install
        npm ls
        npm test
      env:
        CI: true
